version: '3.9'

services:
  produto-api:
    build: .
    ports:
      - 3004:3004
    env_file:
      - .env.docker
    depends_on:
      - produtos-db
  produtos-db:
    image: postgres:16.4
    container_name: produtos_db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
volumes:
  .docker: